import type { Metadata } from "next";
import { Alexandria, Ruwudu } from "next/font/google";
import "./globals.css";

const alexandria = Alexandria({
  variable: "--font-alexandria",
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "600", "700"],
});

const ruwudu = Ruwudu({
  variable: "--font-ruwudu",
  subsets: ["arabic", "latin"],
  weight: ["500"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ar"
      className={`${alexandria.className} ${ruwudu.variable} bg-white h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
